AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

######################### Parameters ##########################
Parameters:
  TargetEnvironment:
    Description: Name of your target environment which will be used as a suffix on created resources (dev, UAT, prod, ...)
    Type: String
    Default: prod
  ZendeskEmailID:
    Type: String
    Description:  Verified email address of a Zendesk agent or admin for the selected Zendesk Instance
  ZendeskToken:
    Type: String
    Description: Zendesk Token for API access. This needs to be generated as a pre-requisite for this installation.
    NoEcho: true
  ZendeskURL:
    Type: String
    Description: Zendesk URL (https://<your-name>.zendesk.com).The Zendesk instance needs to be created as a pre-requisite for this installation.
    AllowedPattern: "https://[a-zA-Z0-9-.]+.zendesk.com$"
    ConstraintDescription: "Endpoint must be a valid Zendesk Host URL. For example, https://voicefoundryap.zendesk.com"
  RecentTicketsHours:
    Type: Number
    Description: Time span (in hours) within which to search for recently updated open tickets
    Default: 72
  
######################### Metadata ############################
Metadata:
  'AWS::ServerlessRepo::Application':
    Name: Zendesk-search-for-Connect-contact-flows
    Description: Enables searching for Zendesk users and tickets within Amazon Connect's contact flows. To be used with Amazon Connect app for Zendesk.
    Author: TTEC Digital - AWS Practice
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['Connect','search', 'Zendesk', 'Support-ticket', 'Contact-flow']
    HomePageUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/tree/master/add-ons/zendesk-search
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/voicefoundryap/amazon-connect-for-zendesk/tree/master/add-ons/zendesk-search

Resources:

  ######################### Lambda ##########################
  functionZendeskSearch:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "zendeskSearchInContactFlow-${TargetEnvironment}"
      Description: "Triggered from Connect contact flow, it searches Zendesk Support API for tickets and users"
      Runtime: nodejs16.x
      Handler: index.handler
      CodeUri: zendeskApi/
      Timeout: 8
      Policies: 
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ZD_EMAIL: !Ref ZendeskEmailID
          ZD_TOKEN: !Ref ZendeskToken 
          ZD_URL: !Ref ZendeskURL
          RECENT_TICKETS_HOURS: !Ref RecentTicketsHours
